[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/mattermost/mattermost-server"
  version = "~5.4.0"

[[override]]
  name = "go.uber.org/zap"
  source = "https://github.com/uber-go/zap"
