[[constraint]]
  name = "github.com/mattermost/mattermost-server"
  version = "~5.3.0"
[[override]]
  name = "go.uber.org/zap"
  source = "https://github.com/uber-go/zap"
[prune]
  go-tests = true
  unused-packages = true
